spring.application.name=TodoApplication

#these things are needed to get the path for view/jsp pages prefix for path and suffix for file extension
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

#here org.springframework represents the package and  
#logging.level represents the level of logging
# we can give our package name instead of org.springframework like logging.level.com.dhapplications.TodoApplication = debug
logging.level.org.springframework=info
#to set the uniform date format across th applucation
spring.mvc.format.date=yyyy-MM-dd

#spring.datasource.url=jdbc:h2:mem:testdb
#to generate the sql after initializing the entity
spring.jpa.defer-datasource-initialization=true

spring.datasource.url=jdbc:mysql://localhost:3306/todos
spring.datasource.username=todos-user
spring.datasource.password=dummytodos
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

#docker run --detach 
#--env MYSQL_ROOT_PASSWORD=dummypassword 
#--env MYSQL_USER=todos-user 
#--env MYSQL_PASSWORD=dummytodos
# --env MYSQL_DATABASE=todos 
# --name mysql 
# --publish 3306:3306 mysql:8-oracle